### ISSUE TITLE
Can we please get a reasonable readme

### ISSUE THREAD

**Issue by timker** [sevenwestmedia-labs/typescript-object-validator#2]
I would like to see examples,
and problems this solves.

**Comment by Tombre** [comment]
Hey @timker, I've just put up a PR for this (we wanted to release the package first). You can check it out here: https://github.com/sevenwestmedia-labs/typescript-object-validator/pull/3

I've added you as a reviewer :)

**Comment by Tombre** [comment]
#3 is merged now, closing this issue 👍
